//
// Created by mathi on 3-9-2026.
//

#include "Serialization.h"

#include <fstream>
#include <string>
#include <unordered_map>
#include <vector>

#include <nlohmann/json.hpp>

#include "Bron/Core/Logger.h"
#include "Bron/Graphics/Components/ModelLoader.h"
#include "Bron/Util/Paths.h"

namespace bron {
namespace {
// Bumped whenever the layout below changes in a way older files cannot satisfy.
constexpr int kSceneVersion = 1;

// Depth first, so siblings land in the file in their current order and can
// simply be re-parented in that order on the way back in.
void WriteEntity(const Scene& scene, const entt::entity entity, nlohmann::json& out) {
	const entt::registry& reg = scene.reg;
	const HierarchyComponent& hierarchy = reg.get<HierarchyComponent>(entity);

	nlohmann::json entry;
	entry["id"] = reg.get<IDComponent>(entity).id;
	entry["name"] = reg.get<TagComponent>(entity).name;
	entry["transform"] = reg.get<TransformComponent>(entity);
	entry["parent"] = hierarchy.parent == entt::null ? nlohmann::json(nullptr)
													 : nlohmann::json(reg.get<IDComponent>(hierarchy.parent).id);

	if (const PointLightComponent* light = reg.try_get<PointLightComponent>(entity)) {
		entry["pointLight"] = *light;
	}

	const ModelSourceComponent* model = reg.try_get<ModelSourceComponent>(entity);
	if (model != nullptr) {
		entry["model"] = *model;
	}

	out.push_back(std::move(entry));

	// Everything below a model is generated by ModelLoader, so the source is
	// recorded and the subtree skipped.
	if (model != nullptr) {
		return;
	}

	for (const entt::entity child: hierarchy.children) {
		WriteEntity(scene, child, out);
	}
}
} // namespace

void Serialization::SerializeScene(const Scene& scene, const std::filesystem::path& file) {
	nlohmann::json entities = nlohmann::json::array();

	// Only what hangs off the root is part of the scene; anything unparented is
	// scratch and is not written.
	if (scene.root != entt::null) {
		WriteEntity(scene, scene.root, entities);
	}

	nlohmann::json document;
	document["version"] = kSceneVersion;
	document["root"] = scene.root == entt::null ? nlohmann::json(nullptr)
												: nlohmann::json(scene.reg.get<IDComponent>(scene.root).id);
	document["entities"] = std::move(entities);

	std::ofstream stream(file);
	if (!stream) {
		BR_CORE_ERROR("Could not open {} for writing", file.string());
		return;
	}

	stream << document.dump(1, '	');
	BR_CORE_INFO("Saved scene to {}", file.string());
}

void Serialization::DeserializeScene(Scene& scene, const std::filesystem::path& file) {
	std::ifstream stream(file);
	if (!stream) {
		BR_CORE_ERROR("Could not open {} for reading", file.string());
		return;
	}

	const nlohmann::json document = nlohmann::json::parse(stream, nullptr, false);
	if (document.is_discarded()) {
		BR_CORE_ERROR("{} is not valid json", file.string());
		return;
	}

	if (document.value("version", 0) != kSceneVersion) {
		BR_CORE_ERROR("{} is a version {} scene, this build reads version {}", file.string(),
					  document.value("version", 0), kSceneVersion);
		return;
	}

	const nlohmann::json& entities = document.at("entities");

	scene.reg.clear();
	scene.root = entt::null;

	std::unordered_map<std::string, entt::entity> by_id;
	std::vector<entt::entity> created;
	created.reserve(entities.size());

	// Every entity has to exist before any parent can be resolved, so the
	// hierarchy is wired up in a second pass.
	for (const nlohmann::json& entry: entities) {
		const entt::entity entity = scene.reg.create();

		scene.reg.emplace<IDComponent>(entity, entry.at("id").get<UUID>());
		scene.reg.emplace<TagComponent>(entity, entry.at("name").get<std::string>());
		scene.reg.emplace<TransformComponent>(entity, entry.at("transform").get<TransformComponent>());
		scene.reg.emplace<HierarchyComponent>(entity);

		if (entry.contains("pointLight")) {
			scene.reg.emplace<PointLightComponent>(entity, entry.at("pointLight").get<PointLightComponent>());
		}

		if (entry.contains("model")) {
			scene.reg.emplace<ModelSourceComponent>(entity, entry.at("model").get<ModelSourceComponent>());
		}

		by_id.emplace(entry.at("id").get<std::string>(), entity);
		created.push_back(entity);
	}

	for (std::size_t i = 0; i < created.size(); ++i) {
		const nlohmann::json& parent = entities[i].at("parent");
		if (parent.is_null()) {
			continue;
		}

		const auto it = by_id.find(parent.get<std::string>());
		if (it == by_id.end()) {
			BR_CORE_WARN("Entity {} names a parent that is not in the file", entities[i].value("name", ""));
			continue;
		}

		scene.AddChild(it->second, created[i]);
	}

	// Re-import the models. load_model builds its own root, so its meshes are
	// moved under the entity that was restored from the file and that root is
	// dropped: the saved transform is the one the user placed, not the centroid
	// the importer would compute again.
	for (std::size_t i = 0; i < created.size(); ++i) {
		if (!scene.reg.all_of<ModelSourceComponent>(created[i])) {
			continue;
		}

		const ModelSourceComponent& source = scene.reg.get<ModelSourceComponent>(created[i]);
		const std::filesystem::path path = paths::Resolve(source.path);

		const entt::entity imported = ModelLoader::LoadModel(scene, source.workflow, path.string().c_str());

		// Copied, because AddChild mutates the vector it is read from.
		const std::vector<entt::entity> meshes = scene.reg.get<HierarchyComponent>(imported).children;
		for (const entt::entity mesh: meshes) {
			scene.AddChild(created[i], mesh);
		}

		scene.DestroyEntity(imported);
	}

	if (const nlohmann::json& root = document.at("root"); !root.is_null()) {
		const auto it = by_id.find(root.get<std::string>());
		if (it != by_id.end()) {
			scene.root = it->second;
		}
	}

	if (scene.root == entt::null) {
		BR_CORE_WARN("{} has no root entity; the scene has no place to parent new entities", file.string());
	}

	BR_CORE_INFO("Loaded scene from {}", file.string());
}
} // namespace bron
