# Writes a header and a translation unit holding the bytes of a set of files. Run in
# script mode by bron_embed_resources(); see cmake/EmbedResources.cmake for the why and
# for the arguments, which are passed as -D on the command line:
#
#   INPUTS     the files to embed, absolute, separated by "|" (";" cannot survive -D)
#   HEADER     the .h to write
#   SOURCE     the .cpp to write
#   NAMESPACE  the C++ namespace both live in

cmake_minimum_required(VERSION 3.21)

foreach(argument INPUTS HEADER SOURCE NAMESPACE)
	if(NOT DEFINED ${argument})
		message(FATAL_ERROR "GenerateEmbeddedResources: -D${argument} is required")
	endif()
endforeach()

# "add" -> "kAdd", "arrow_up" -> "kArrowUp". The symbol has to be a valid identifier and
# has to read like the rest of the codebase, so the stem is title cased word by word.
function(symbol_for stem out)
	string(REPLACE "_" ";" words "${stem}")

	set(symbol "k")
	foreach(word ${words})
		string(SUBSTRING "${word}" 0 1 first)
		string(SUBSTRING "${word}" 1 -1 rest)
		string(TOUPPER "${first}" first)
		string(APPEND symbol "${first}${rest}")
	endforeach()

	set(${out} "${symbol}" PARENT_SCOPE)
endfunction()

# One row of the generated array. CMake's regex flavour has no {n} repetition, so the
# twelve bytes a line holds are spelled out by repeating the pattern.
set(byte "0x[0-9a-f][0-9a-f],")
string(REPEAT "${byte}" 12 row)

set(banner "// Generated by cmake/GenerateEmbeddedResources.cmake. Do not edit: change the\n// file it was made from, or the bron_embed_resources() call that names it.\n")

get_filename_component(header_name "${HEADER}" NAME)

set(declarations "")
set(definitions "")

string(REPLACE "|" ";" inputs "${INPUTS}")
foreach(input ${inputs})
	get_filename_component(stem "${input}" NAME_WE)
	get_filename_component(filename "${input}" NAME)
	symbol_for("${stem}" symbol)

	file(READ "${input}" bytes HEX)

	# "0a1b" -> "0x0a,0x1b,", then a line break every twelve bytes so the generated file
	# can still be opened without hanging an editor on one enormous line.
	string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${bytes}")
	string(REGEX REPLACE "(${row})" "\\1\n\t\t" bytes "${bytes}")

	string(APPEND declarations "\n/// The contents of ${filename}.\nextern const Resource ${symbol};\n")
	string(APPEND definitions "\nconstexpr unsigned char ${symbol}Bytes[]{\n\t\t${bytes}\n};\n")
	string(APPEND accessors "\nconst Resource ${symbol}{${symbol}Bytes, sizeof(${symbol}Bytes)};\n")
endforeach()

file(WRITE "${HEADER}" "${banner}
#pragma once

#include <cstddef>

namespace ${NAMESPACE} {
/// A file that was built into the binary. The bytes are the file's own, untouched, so
/// they still need whatever decoder the format calls for.
struct Resource {
	const unsigned char* data;
	std::size_t size;
};
${declarations}} // namespace ${NAMESPACE}
")

file(WRITE "${SOURCE}" "${banner}
#include \"${header_name}\"

namespace ${NAMESPACE} {
namespace {
${definitions}} // namespace
${accessors}} // namespace ${NAMESPACE}
")
